// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYDAwPMICJZwERiL7wOjWr3kse-fg5IkI',
    appId: '1:94676476141:web:6eab01cc1d74fe884c2ce4',
    messagingSenderId: '94676476141',
    projectId: 'chat-dosen-b9cd5',
    authDomain: 'chat-dosen-b9cd5.firebaseapp.com',
    storageBucket: 'chat-dosen-b9cd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJqqXcXg5MNfylomJPaIi44Ihpl5Gi0Is',
    appId: '1:94676476141:android:6bf5b8076274a3054c2ce4',
    messagingSenderId: '94676476141',
    projectId: 'chat-dosen-b9cd5',
    storageBucket: 'chat-dosen-b9cd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0JhHikn5vZ-BEXSD2U7nhDFIU3vO2fqk',
    appId: '1:94676476141:ios:91f54cadc32f43784c2ce4',
    messagingSenderId: '94676476141',
    projectId: 'chat-dosen-b9cd5',
    storageBucket: 'chat-dosen-b9cd5.appspot.com',
    iosClientId: '94676476141-b9cddbt1acsc89c2jacj7il79flgl1dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatDosen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0JhHikn5vZ-BEXSD2U7nhDFIU3vO2fqk',
    appId: '1:94676476141:ios:91f54cadc32f43784c2ce4',
    messagingSenderId: '94676476141',
    projectId: 'chat-dosen-b9cd5',
    storageBucket: 'chat-dosen-b9cd5.appspot.com',
    iosClientId: '94676476141-b9cddbt1acsc89c2jacj7il79flgl1dq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatDosen',
  );
}
